# Generated by Django 5.2.1 on 2025-05-12 05:03

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownfield.models.MarkdownField(rendered_field='body_rendered'),
        ),
    ]
